### ISSUE TITLE
Conflict with cJSON project

### ISSUE THREAD

**Issue by alb423** [hmng/jsonrpc-c#20]
The cJSON project has a different definition which conflict with this project.

For example:
jsonrpc-c/cJON.h
#define cJSON_NUMBER 3
cJSON/cJON.h
#define cJSON_NUMBER (1<<3)

May you help to upgrade cJSON.c/cJSON.h to sync with the cJSON project?

**Comment by hmng** [comment]
I have pulled in the latest cJSON. Let me know if you still see any issues.
