### ISSUE TITLE
jsonrpc-c support notification?

### ISSUE THREAD

**Issue by mathben** [hmng/jsonrpc-c#4]
Hi, 
can you answer me if jsonrpc-c support notification and how use it?
Like this JSON-RPC v.2 : http://en.wikipedia.org/wiki/JSON-RPC#Version_2.0

Thanks

**Comment by hmng** [comment]
Implemented in 7438987306c4461b5f564cb6d3ef5b19fb53f593 If a procedure returns NULL, no reply is sent. Is up to the procedure to decide (based on "id" field or other criteria) if a reply is needed.
